### ISSUE TITLE
HTML chapter preview stopped working

### ISSUE THREAD

**Issue by jackkinsella** [adamniedzielski/admission#8]
This actually happened about a week ago (or more). I think it might correlate with me changing the ToC settings.

```
pandoc: build/previews/1-1-Search Engine Optimisation Introduction.html: openFile: does not exist (No such file or directory)
** (MatchError) no match of right hand side value: {"", 1}
    (admission) lib/admission/builder.ex:71: Admission.Builder.generate_html_preview/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (admission) lib/admission.ex:12: Admission.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by adamniedzielski** [comment]
I can build the book on my computer.
Did you by chance remove `build/previews` directory? I get the same error when I remove this directory. There is a `.keep`file inside to make sure that it's not removed from git repo.

**Comment by jackkinsella** [comment]
that did the trick. Thanks :)
